### ISSUE TITLE
Missing delimiter in text exports

### ISSUE THREAD

**Issue by hbarsnes** [compomics/COSS#4]
A delimiter is missing in the text export, resulting in the output containing output such as:
ILCEQCMTSNQK806.834444901547.

Should be fixed by changing `fileOut.write(mSpec.get(s).getSequence());` into `fileOut.write(mSpec.get(s).getSequence() +  delim);`

See: https://github.com/compomics/COSS/blob/master/src/main/java/com/compomics/coss/controller/ImportExport.java#L301

**Comment by Genet-Abay** [comment]
Thank you very much for all your comments and ideas.  The delimiter is now added and hence output is corrected in csv and tab-delimited format .

**Comment by hbarsnes** [comment]
Thanks for the fix!

There was one more delimiter missing in the tsv export though, after the modifications column. Corrected in https://github.com/compomics/COSS/commit/da6164901f086e20bf512a9dbfa62ce9d6342299 :)
