### ISSUE TITLE
Mods tags in msp files are not output correctly in the exports

### ISSUE THREAD

**Issue by hbarsnes** [compomics/COSS#5]
In all of the exports the Mods tags from msp files are often changed compared to the original lines in the msp file.

For example, in the human msp file from PRIDE one can find the following:

```
Name: ILCEQCMTSNQK/2
MW: 1611.6440341796874
Comment: Spec=Consensus Mods=3/2,C,89.011293/5,C,89.011293/6,M,37.006603 [...]
```

However, in the results export from COSS the information in this specific Mods tag is changed into:

`3/2,C,/5,C,/6,M,`

In other words, skipping the mass shift of the modification. Which makes it impossible to figure out what the original modifications were.

**Comment by Genet-Abay** [comment]
Yes, that is right.  PRIDE human.msp file has a mixed description of Mods field and I had to handle that. Now it is working correctly.

**Comment by hbarsnes** [comment]
Thanks! I will test as soon as the issue with the missing rows in the text export has been solved: https://github.com/compomics/COSS/issues/8

Re-opening the issue only so that I remember to re-test. :)
