### ISSUE TITLE
The spectrum title includes the TITLE tag in the exports

### ISSUE THREAD

**Issue by hbarsnes** [compomics/COSS#6]
When using mgf as input the TITLE tag should not be included when exporting the results.

In other words, mgf spectrum titles such as:

`TITLE=qExactive01819.5779.5779.3 File:"qExactive01819.raw", NativeID:"controllerType=0 controllerNumber=1 scan=5779"`

ought to show up in the Title column in the exports as:

`qExactive01819.5779.5779.3 File:"qExactive01819.raw", NativeID:"controllerType=0 controllerNumber=1 scan=5779"`

**Comment by Genet-Abay** [comment]
TITLE tag now removed from the output.

**Comment by hbarsnes** [comment]
Thanks!
